# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20180321_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
