# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20180321_1358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='tasks_text',
            new_name='task_text',
        ),
    ]
