# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20180321_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('D', 'Daily'), ('M', 'Monthly'), ('Y', 'Yearly')], default='D', max_length=10),
        ),
    ]
