# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('D', 'Daily'), ('M', 'Monthly'), ('Y', 'Yearly'), ('O', 'Once')], default='D', max_length=10),
        ),
    ]
