# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20180321_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('Once', 'Once')], default='Daily', max_length=10),
        ),
    ]
